---
title: "Setup"
format: 
  revealjs: 
    theme: style.scss
    multiplex: true
    transition: fade
editor: visual
---

## Setup

-   This section contains some setup information to be used during the preparation of the talk
-   Will be removed before finalizing the talk

## Color palette

Tested for six common types of color blindness.

```{r}
#| label: load-pkg
#| warning: false

library(tidyverse)
```

```{r}
#| out.width: "100%"

df <- tribble(
  ~color,    ~name,                   ~text_color, 
  "#FF744E", "OPENSCAPES ORANGE",           "black",
  "#FAE3E3", "MISTY ROSE",            "black",
  "#607576", "CADET",                 "black",
  "#1C1C1C", "EERIE BLACK",           "white",
  "#75AADB", "QUARTO BLUE",           "black"
)

ggplot(df, aes(y = fct_inorder(color), x = 10, fill = color)) +
  geom_col() +
  scale_fill_identity() +
  theme_void() +
  geom_text(aes(x = 1, label = paste(color, "-", name), color = text_color), hjust = 0, fontface = "bold") +
  scale_color_identity()
```

## Video embed {background-video="test-video.mp4" background-video-loop="true" background-video-muted="true"}